name: Test Workflow

on: 
  push:
    branches:
      - main

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      # Step 1: Checkout Repository
      - name: Checkout Repository
        uses: actions/checkout@v3

      # Step 2: Set Up Python
      - name: Set Up Python
        uses: actions/setup-python@v3
        with:
          python-version: '3.x'

      # Step 3: Run Tests
      - name: Run Test 1: File with 10 numbers
        run: |
          python3 find_lowest_number_project/find_min_number.py find_lowest_number_project/test_data/test1_input.txt output1.txt
          diff output1.txt find_lowest_number_project/test_data/test1_expected.txt

      - name: Run Test 2: File with 1 number
        run: |
          python3 find_lowest_number_project/find_min_number.py find_lowest_number_project/test_data/test2_input.txt output2.txt
          diff output2.txt find_lowest_number_project/test_data/test2_expected.txt

      - name: Run Test 3: Blank file
        run: |
          python3 find_lowest_number_project/find_min_number.py find_lowest_number_project/test_data/test3_input.txt output3.txt
          diff output3.txt find_lowest_number_project/test_data/test3_expected.txt
